on:
  release:
    types: [created]

      # Trigger the workflow on push or pull request,
  # but only for the master branch
  #push:
  #  branches:
  #    - master
  #pull_request:
  #  branches:
  #    - master

name: Linux_Container_Node_Workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action' 
      uses: actions/checkout@master
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_DEV }}
    
    - uses: azure/docker-login@v1
      with:
        login-server: testdomain.azurecr.io
        username: ${{ secrets.DOCKER_Username }}
        password: ${{ secrets.DOCKER_Password }}
    
    - run: |
        docker build . -t testdomain.azurecr.io/nodejssampleapp:${{ github.sha }}
        docker push testdomain.azurecr.io/nodejssampleapp:${{ github.sha }} 
      
    - uses: azure/webapps-container-deploy@v1
      with:
        app-name: 'test-domain'
        images: 'testdomain.azurecr.io/nodejssampleapp:${{ github.sha }}'
    
    - name: Azure logout
      run: |
        az logout
